/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.VitalSignHistory;
import model.VitalSigns;

/**
 *
 * @author Aishwarya
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    VitalSignHistory history;
    public CreateJPanel(VitalSignHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbTemperature = new javax.swing.JLabel();
        lbPressure = new javax.swing.JLabel();
        lbPulse = new javax.swing.JLabel();
        lbDate = new javax.swing.JLabel();
        txtTemperature = new javax.swing.JTextField();
        txtPressure = new javax.swing.JTextField();
        txtPluse = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lbTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("Create Vital Signs");

        lbTemperature.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbTemperature.setText("Temperature:");

        lbPressure.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbPressure.setText("Blood Pressure:");

        lbPulse.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbPulse.setText("Pluse:");

        lbDate.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lbDate.setText("Date:");

        btnSave.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbDate)
                    .addComponent(lbPulse)
                    .addComponent(lbPressure)
                    .addComponent(lbTemperature))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPluse, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbTitle)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTemperature)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPressure)
                    .addComponent(txtPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPluse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPulse))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDate))
                .addGap(42, 42, 42)
                .addComponent(btnSave)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(txtTemperature.getText().isEmpty()|| txtPressure.getText().isEmpty()||txtPluse.getText().isEmpty() ||txtDate.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fillup all the fields","Error",JOptionPane.ERROR_MESSAGE);
        } else {
            // Body Temperature considered upto 109
            String temperaturematch = "^([0-9]{1,2}(?:\\.[0-9]{1,2})?$)|(1[00][0-9]{1,2}(?:\\.[0-9]{1,3})?$)"; 
            Pattern tempValidate = Pattern.compile(temperaturematch);
            Matcher tempmatcher = tempValidate.matcher(txtTemperature.getText());
            Boolean tempValue = tempmatcher.matches();
            
            // Blood Presssure considered upto 199
            String pressureMatch = "^([1-9]|[1-9][0-9]|1[99][0-9])"; 
            Pattern pressValidate = Pattern.compile(pressureMatch);
            Matcher pressurematcher = pressValidate.matcher(txtPressure.getText());
            Boolean pressureValue = pressurematcher.matches();
            
            // date in Month Day, Year format
            String datematch = "((Jan(uary)?|Feb(ruary)?|Mar(ch)?|Apr(il)?|May|Jun(e)?|Jul(y)?|Aug(ust)?|Sep(tember)?|Oct(ober)?|Nov(ember)?|Dec(ember)?)\\s+\\d{1,2},\\s+\\d{4})|((1[0-2]|0?[1-9])/(3[01]|[12][0-9]|0?[1-9])/(?:[0-9]{2})?[0-9]{2})";
            Pattern dateValidate = Pattern.compile(datematch);
            Matcher dateMatcher = dateValidate.matcher(txtDate.getText());
            Boolean dateValue = dateMatcher.matches();
            
            // Pluse in integer upto 299
            String pulsematch = "^([0-9]{1,2}?$)|(1[0-9]{1,2}?$)|(2[0-9]{1,2}?$)";
            Pattern pluseValidate = Pattern.compile(pulsematch);
            Matcher pluseMatcher = pluseValidate.matcher(txtPluse.getText());
            Boolean pluseValue = pluseMatcher.matches();

            if(tempValue == false){
                JOptionPane.showMessageDialog(null, "Please enter valid Temperature","Error",JOptionPane.ERROR_MESSAGE);
            }else if(pressureValue == false){
                JOptionPane.showMessageDialog(null, "Please enter valid Blood Pressure","Error",JOptionPane.ERROR_MESSAGE);
            }else if (pluseValue == false){
                JOptionPane.showMessageDialog(null, "Please enter valid Pluse Rate","Error",JOptionPane.ERROR_MESSAGE);
            }else if (dateValue == false){
                JOptionPane.showMessageDialog(null, "Please enter valid Date in Month Day, Year format","Error",JOptionPane.ERROR_MESSAGE);
            }else {
                double temperature = Double.parseDouble(txtTemperature.getText());
                double pressure = Double.parseDouble(txtPressure.getText());
                int pulse = Integer.parseInt(txtPluse.getText());
                String Date = txtDate.getText();
                
                VitalSigns vs = history.addNewVital();
                vs.setTemperature(temperature);
                vs.setBloodPressure(pressure);
                vs.setPulse(pulse);
                vs.setDate(Date);

                JOptionPane.showMessageDialog(this, "New Vital Sign added.");

                txtTemperature.setText("");
                txtPressure.setText("");
                txtPluse.setText("");
                txtDate.setText("");
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbDate;
    private javax.swing.JLabel lbPressure;
    private javax.swing.JLabel lbPulse;
    private javax.swing.JLabel lbTemperature;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPluse;
    private javax.swing.JTextField txtPressure;
    private javax.swing.JTextField txtTemperature;
    // End of variables declaration//GEN-END:variables
}
