/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.person;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.person.City;
import model.person.Community;
import model.person.House;
import model.person.Person;
import model.person.PersonDirectory;

/**
 *
 * @author dhairyasheel
 */
public class PersonDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonDirectoryJPanel
     */
     JPanel mainWorkArea;
     PersonDirectory personDirectory;
     City city;
     Community community;
     List<Person> personList;
     House house;
     
    public PersonDirectoryJPanel(JPanel mainWorkArea,PersonDirectory personDirectory) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.personDirectory = personDirectory;
        personList = personDirectory.getPersonList();
        populateCombo();
        refreshTable();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        personDirPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        communityJC = new javax.swing.JComboBox<>();
        btnAddPer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        btnDeletePer = new javax.swing.JButton();
        btnViewPer = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        personPanel = new javax.swing.JPanel();

        SplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        personDirPanel.setBackground(new java.awt.Color(254, 254, 254));

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(109, 144, 149));
        lblTitle.setText("Person Directory");

        communityJC.setBackground(new java.awt.Color(254, 254, 254));
        communityJC.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        communityJC.setForeground(new java.awt.Color(120, 149, 162));
        communityJC.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        communityJC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityJCActionPerformed(evt);
            }
        });

        btnAddPer.setBackground(new java.awt.Color(254, 254, 254));
        btnAddPer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAddPer.setForeground(new java.awt.Color(100, 149, 162));
        btnAddPer.setText("Add Person");
        btnAddPer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPerActionPerformed(evt);
            }
        });

        tblPerson.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        tblPerson.setForeground(new java.awt.Color(100, 149, 162));
        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Person ID", "Name", "Date of Birth", "Community"
            }
        ));
        tblPerson.setGridColor(new java.awt.Color(136, 168, 179));
        tblPerson.setSelectionForeground(new java.awt.Color(100, 149, 162));
        jScrollPane1.setViewportView(tblPerson);

        btnDeletePer.setBackground(new java.awt.Color(254, 254, 254));
        btnDeletePer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnDeletePer.setForeground(new java.awt.Color(100, 149, 162));
        btnDeletePer.setText("Delete");
        btnDeletePer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDeletePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletePerActionPerformed(evt);
            }
        });

        btnViewPer.setBackground(new java.awt.Color(254, 254, 254));
        btnViewPer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnViewPer.setForeground(new java.awt.Color(100, 149, 162));
        btnViewPer.setText("View");
        btnViewPer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnViewPer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPerActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(254, 254, 254));
        btnLogout.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(229, 70, 69));
        btnLogout.setText("LOGOUT");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout personDirPanelLayout = new javax.swing.GroupLayout(personDirPanel);
        personDirPanel.setLayout(personDirPanelLayout);
        personDirPanelLayout.setHorizontalGroup(
            personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personDirPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(personDirPanelLayout.createSequentialGroup()
                        .addComponent(communityJC, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(personDirPanelLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, personDirPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))
                    .addGroup(personDirPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDeletePer, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(btnViewPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        personDirPanelLayout.setVerticalGroup(
            personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(personDirPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityJC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddPer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(personDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(personDirPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnViewPer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeletePer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(personDirPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        SplitPane.setTopComponent(personDirPanel);

        personPanel.setBackground(new java.awt.Color(254, 254, 254));

        javax.swing.GroupLayout personPanelLayout = new javax.swing.GroupLayout(personPanel);
        personPanel.setLayout(personPanelLayout);
        personPanelLayout.setHorizontalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );
        personPanelLayout.setVerticalGroup(
            personPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(personPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SplitPane)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPerActionPerformed
       CreatePersonJPanel selectedPanel =new  CreatePersonJPanel (mainWorkArea,personDirectory);
        mainWorkArea.add("PersonDirectoryJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnAddPerActionPerformed

    private void btnDeletePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletePerActionPerformed
        // TODO add your handling code here:
        int row = tblPerson.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person s = (Person)tblPerson.getValueAt(row, 0);
        personDirectory.removeSupplier(s);
        refreshTable();
    }//GEN-LAST:event_btnDeletePerActionPerformed

    private void btnViewPerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPerActionPerformed
        int row = tblPerson.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Person c = (Person)tblPerson.getValueAt(row, 0);
        
        ViewPersonJPanel viewPerson = new ViewPersonJPanel(mainWorkArea,c);
        SplitPane.setBottomComponent(viewPerson);
    }//GEN-LAST:event_btnViewPerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        mainWorkArea.remove(this);
        CardLayout layout = (CardLayout)mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void communityJCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityJCActionPerformed
        // TODO add your handling code here:
        refreshTable();
    }//GEN-LAST:event_communityJCActionPerformed

    public void refreshTable() {
        String selectedSupplier = (String) communityJC.getSelectedItem();
        if("All Communities".equals(selectedSupplier)){
            DefaultTableModel model = (DefaultTableModel)tblPerson.getModel();
            model.setRowCount(0);
            for(Person p: personDirectory.getPersonList()) {
                Object row[] = new Object[4];
                row[0] = p;
                row[1] = p.getName();
                row[2] = p.getDate();
                row[3] = p.getAddress().getCommunity();
               // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
                model.addRow(row);
            }
        } else {
            DefaultTableModel model = (DefaultTableModel)tblPerson.getModel();
            model.setRowCount(0);
            for(Person p: personDirectory.getPersonList()) {
                if(p.getAddress().getCommunity().equals(selectedSupplier)){
                    Object row[] = new Object[4];
                    row[0] = p;
                    row[1] = p.getName();
                    row[2] = p.getDate();
                    row[3] = p.getAddress().getCommunity();
                   // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
                    model.addRow(row);
                } 
                
            }
        }
    }

    public void populateCombo() {
        communityJC.removeAllItems();
        communityJC.addItem("All Communities");

        List<String> sorted = new ArrayList<>();
        for(Person s: personList){
            if(!sorted.contains(s.getAddress().getCommunity())){
                sorted.add(s.getAddress().getCommunity());
            }
        }
       for(String s: sorted){
           communityJC.addItem(s);
        }
       refreshTable();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnAddPer;
    private javax.swing.JButton btnDeletePer;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewPer;
    private javax.swing.JComboBox<String> communityJC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel personDirPanel;
    private javax.swing.JPanel personPanel;
    private javax.swing.JTable tblPerson;
    // End of variables declaration//GEN-END:variables
}
