/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.person;

import java.awt.CardLayout;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import model.person.City;
import model.person.Community;
import model.person.Person;
import model.person.PersonDirectory;

/**
 *
 * @author dhairyasheel
 */
public class ViewPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonJPanel
     */
    JPanel mainWorkArea;
    Person person;
    public ViewPersonJPanel(JPanel mainWorkArea,Person person) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.person = person;
       
        txtID.setText(String.valueOf(person.getId()));
        txtName.setText(person.getName());
        txtAge.setText(String.valueOf(person.getAge()));
        txtDOB.setText(person.getDate());
        txtGender.setText(person.getGender());
        
        txtCity.setText(person.getAddress().getCity());
        txtState.setText(person.getAddress().getState());
        txtCom.setText(person.getAddress().getCommunity());
        txtPin.setText(String.valueOf(person.getAddress().getPin()));
        txtStreet.setText(person.getAddress().getStreet());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PersonaljPanel3 = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        txtDOB = new javax.swing.JTextField();
        PersonaljPanel4 = new javax.swing.JPanel();
        txtStreet = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        txtPin = new javax.swing.JTextField();
        lblCom = new javax.swing.JLabel();
        txtCom = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        btnUpadatePer = new javax.swing.JButton();

        setBackground(new java.awt.Color(254, 254, 254));

        PersonaljPanel3.setBackground(new java.awt.Color(254, 254, 254));
        PersonaljPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        txtID.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtID.setForeground(new java.awt.Color(63, 83, 125));
        txtID.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtID.setEnabled(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        lblID.setBackground(new java.awt.Color(254, 254, 254));
        lblID.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(114, 150, 180));
        lblID.setText("Unique Person ID:");

        lblName.setBackground(new java.awt.Color(254, 254, 254));
        lblName.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(114, 150, 180));
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtName.setForeground(new java.awt.Color(63, 83, 125));
        txtName.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtName.setEnabled(false);

        lblDOB.setBackground(new java.awt.Color(254, 254, 254));
        lblDOB.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(114, 150, 180));
        lblDOB.setText("Date of Birth:");

        txtAge.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtAge.setForeground(new java.awt.Color(63, 83, 125));
        txtAge.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtAge.setEnabled(false);

        lblAge.setBackground(new java.awt.Color(254, 254, 254));
        lblAge.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(114, 150, 180));
        lblAge.setText("Age:");

        lblGender.setBackground(new java.awt.Color(254, 254, 254));
        lblGender.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        lblGender.setForeground(new java.awt.Color(114, 150, 180));
        lblGender.setText("Gender:");

        txtGender.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtGender.setForeground(new java.awt.Color(63, 83, 125));
        txtGender.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtGender.setEnabled(false);

        txtDOB.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtDOB.setForeground(new java.awt.Color(63, 83, 125));
        txtDOB.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtDOB.setEnabled(false);

        javax.swing.GroupLayout PersonaljPanel3Layout = new javax.swing.GroupLayout(PersonaljPanel3);
        PersonaljPanel3.setLayout(PersonaljPanel3Layout);
        PersonaljPanel3Layout.setHorizontalGroup(
            PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanel3Layout.createSequentialGroup()
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanel3Layout.createSequentialGroup()
                        .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonaljPanel3Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDOB)
                                    .addComponent(lblName)))
                            .addComponent(lblID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtID)
                                .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonaljPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PersonaljPanel3Layout.setVerticalGroup(
            PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDOB)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGender)
                    .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PersonaljPanel4.setBackground(new java.awt.Color(254, 254, 254));
        PersonaljPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Address", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        txtStreet.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtStreet.setForeground(new java.awt.Color(63, 83, 125));
        txtStreet.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtStreet.setEnabled(false);

        lblStreet.setBackground(new java.awt.Color(254, 254, 254));
        lblStreet.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(114, 150, 180));
        lblStreet.setText("Street:");

        lblPin.setBackground(new java.awt.Color(254, 254, 254));
        lblPin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblPin.setForeground(new java.awt.Color(114, 150, 180));
        lblPin.setText("Pin code:");

        txtPin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtPin.setForeground(new java.awt.Color(63, 83, 125));
        txtPin.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtPin.setEnabled(false);

        lblCom.setBackground(new java.awt.Color(254, 254, 254));
        lblCom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCom.setForeground(new java.awt.Color(114, 150, 180));
        lblCom.setText("Community:");

        txtCom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtCom.setForeground(new java.awt.Color(63, 83, 125));
        txtCom.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtCom.setEnabled(false);

        txtCity.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtCity.setForeground(new java.awt.Color(63, 83, 125));
        txtCity.setText(" ");
        txtCity.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtCity.setEnabled(false);

        lblCity.setBackground(new java.awt.Color(254, 254, 254));
        lblCity.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCity.setForeground(new java.awt.Color(114, 150, 180));
        lblCity.setText("City:");

        lblState.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(99, 119, 145));
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblState.setText("State:");

        txtState.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtState.setForeground(new java.awt.Color(63, 83, 125));
        txtState.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtState.setDisabledTextColor(new java.awt.Color(65, 97, 132));
        txtState.setEnabled(false);

        javax.swing.GroupLayout PersonaljPanel4Layout = new javax.swing.GroupLayout(PersonaljPanel4);
        PersonaljPanel4.setLayout(PersonaljPanel4Layout);
        PersonaljPanel4Layout.setHorizontalGroup(
            PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblState)
                    .addComponent(lblCom)
                    .addComponent(lblPin)
                    .addComponent(lblCity)
                    .addComponent(lblStreet))
                .addGap(18, 18, 18)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCom, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PersonaljPanel4Layout.setVerticalGroup(
            PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonaljPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPin)
                    .addComponent(txtPin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCom)
                    .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState))
                .addContainerGap())
        );

        btnUpadatePer.setBackground(new java.awt.Color(254, 254, 254));
        btnUpadatePer.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnUpadatePer.setForeground(new java.awt.Color(100, 149, 162));
        btnUpadatePer.setText("Update");
        btnUpadatePer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUpadatePer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpadatePerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(PersonaljPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(PersonaljPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(351, 351, 351)
                        .addComponent(btnUpadatePer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PersonaljPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PersonaljPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpadatePer, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void btnUpadatePerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpadatePerActionPerformed
        // TODO add your handling code here:

        UpdatePersonJPanel selectedPanel = null;
        try {
            selectedPanel = new  UpdatePersonJPanel (mainWorkArea,person);
        } catch (ParseException ex) {
            Logger.getLogger(ViewPersonJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainWorkArea.add("PersonDirectoryJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnUpadatePerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PersonaljPanel3;
    private javax.swing.JPanel PersonaljPanel4;
    private javax.swing.JButton btnUpadatePer;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPin;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
