/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.patient;

import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.patient.Encounter;
import model.patient.Patient;
import model.person.Person;

/**
 *
 * @author dhairyasheel
 */
public class PatientProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientProfileJPanel
     */
    JPanel mainWorkArea;
    Patient patient;
    public PatientProfileJPanel(JPanel mainWorkArea,Patient patient) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        this.patient = patient;
        
        txtID.setText(String.valueOf(patient.getPatient().getId()));
        txtName.setText(patient.getPatient().getName());
        txtAge.setText(String.valueOf(patient.getPatient().getAge()));
        txtAdd1.setText(patient.getPatient().getDate());
        txtGender.setText(patient.getPatient().getGender());
        
        txtAdd.setText(patient.getPatient().getAddress().getStreet());
        txtCity.setText(patient.getPatient().getAddress().getCity());
        txtCom.setText(patient.getPatient().getAddress().getCommunity());
        txtState.setText(String.valueOf(patient.getPatient().getAddress().getState()));
        
       refreshTable(); 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        PersonaljPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistory = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        PersonaljPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        lblAdd = new javax.swing.JLabel();
        txtAdd = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCom = new javax.swing.JTextField();
        lblCom = new javax.swing.JLabel();
        txtState = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();
        txtAdd1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(254, 254, 254));

        lblTitle1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(109, 144, 149));
        lblTitle1.setText("Patient's Profile");

        PersonaljPanel.setBackground(new java.awt.Color(254, 254, 254));
        PersonaljPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Patient's Medical History", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        tblHistory.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        tblHistory.setForeground(new java.awt.Color(100, 149, 162));
        tblHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date of Visit", "Blood Pressure", "Temperature"
            }
        ));
        tblHistory.setGridColor(new java.awt.Color(136, 168, 179));
        tblHistory.setSelectionForeground(new java.awt.Color(100, 149, 162));
        jScrollPane1.setViewportView(tblHistory);

        btnDelete.setBackground(new java.awt.Color(254, 254, 254));
        btnDelete.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(100, 149, 162));
        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(254, 254, 254));
        btnView.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnView.setForeground(new java.awt.Color(100, 149, 162));
        btnView.setText("View Encounter");
        btnView.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(254, 254, 254));
        btnAdd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(100, 149, 162));
        btnAdd.setText(" Add Encounter");
        btnAdd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PersonaljPanelLayout = new javax.swing.GroupLayout(PersonaljPanel);
        PersonaljPanel.setLayout(PersonaljPanelLayout);
        PersonaljPanelLayout.setHorizontalGroup(
            PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanelLayout.createSequentialGroup()
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PersonaljPanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        PersonaljPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnView});

        PersonaljPanelLayout.setVerticalGroup(
            PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PersonaljPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(PersonaljPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnBack.setBackground(new java.awt.Color(254, 254, 254));
        btnBack.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnBack.setForeground(new java.awt.Color(100, 149, 162));
        btnBack.setText("Back");
        btnBack.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        PersonaljPanel1.setBackground(new java.awt.Color(254, 254, 254));
        PersonaljPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Patient's Profile", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(95, 139, 162))); // NOI18N

        txtName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtName.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtName.setEnabled(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblName.setBackground(new java.awt.Color(254, 254, 254));
        lblName.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblName.setForeground(new java.awt.Color(114, 150, 180));
        lblName.setText("Name:");

        lblDOB.setBackground(new java.awt.Color(254, 254, 254));
        lblDOB.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(114, 150, 180));
        lblDOB.setText("Date of Birth:");

        txtAge.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtAge.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtAge.setEnabled(false);

        lblAge.setBackground(new java.awt.Color(254, 254, 254));
        lblAge.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAge.setForeground(new java.awt.Color(114, 150, 180));
        lblAge.setText("Age:");

        lblID.setBackground(new java.awt.Color(254, 254, 254));
        lblID.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblID.setForeground(new java.awt.Color(114, 150, 180));
        lblID.setText("Person ID:");

        txtID.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtID.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtID.setEnabled(false);

        lblGender.setBackground(new java.awt.Color(254, 254, 254));
        lblGender.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblGender.setForeground(new java.awt.Color(114, 150, 180));
        lblGender.setText("Gender:");

        txtGender.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtGender.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtGender.setEnabled(false);
        txtGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGenderActionPerformed(evt);
            }
        });

        lblAdd.setBackground(new java.awt.Color(254, 254, 254));
        lblAdd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblAdd.setForeground(new java.awt.Color(114, 150, 180));
        lblAdd.setText("Address:");

        txtAdd.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtAdd.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtAdd.setEnabled(false);

        txtCity.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtCity.setText("jTextField1");
        txtCity.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtCity.setEnabled(false);
        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblCity.setBackground(new java.awt.Color(254, 254, 254));
        lblCity.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCity.setForeground(new java.awt.Color(114, 150, 180));
        lblCity.setText("City:");

        txtCom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtCom.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtCom.setEnabled(false);
        txtCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComActionPerformed(evt);
            }
        });

        lblCom.setBackground(new java.awt.Color(254, 254, 254));
        lblCom.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblCom.setForeground(new java.awt.Color(114, 150, 180));
        lblCom.setText("Community:");

        txtState.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtState.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtState.setEnabled(false);
        txtState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStateActionPerformed(evt);
            }
        });

        lblState.setBackground(new java.awt.Color(254, 254, 254));
        lblState.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblState.setForeground(new java.awt.Color(114, 150, 180));
        lblState.setText("State:");

        txtAdd1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtAdd1.setDisabledTextColor(new java.awt.Color(79, 99, 135));
        txtAdd1.setEnabled(false);

        javax.swing.GroupLayout PersonaljPanel1Layout = new javax.swing.GroupLayout(PersonaljPanel1);
        PersonaljPanel1.setLayout(PersonaljPanel1Layout);
        PersonaljPanel1Layout.setHorizontalGroup(
            PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblName)
                    .addComponent(lblAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                        .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCom)
                        .addGap(6, 6, 6)
                        .addComponent(txtCom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblState)
                        .addGap(1, 1, 1)
                        .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                .addComponent(lblID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAge, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDOB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                        .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblGender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PersonaljPanel1Layout.setVerticalGroup(
            PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                        .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblID)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PersonaljPanel1Layout.createSequentialGroup()
                        .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOB))
                        .addGap(7, 7, 7)
                        .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblGender))
                            .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblAge)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PersonaljPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(txtCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCom)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblState)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAdd))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(303, 303, 303))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(PersonaljPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PersonaljPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PersonaljPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PersonaljPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         mainWorkArea.remove(this);
        Component[] componentArray = mainWorkArea.getComponents();
        Component component = componentArray[componentArray.length - 1];
        PatientDirectoryJPanel patientDirectoryJPanel = (PatientDirectoryJPanel) component;
        patientDirectoryJPanel.refreshTable();
        patientDirectoryJPanel.populateCombo();
        patientDirectoryJPanel.populateBP();
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.previous(mainWorkArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int row = tblHistory.getSelectedRow();
        
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Encounter encounter = ((Encounter)tblHistory.getValueAt(row, 0));
        patient.removeEncounter(encounter);
        refreshTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int row = tblHistory.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Encounter encounter = ((Encounter)tblHistory.getValueAt(row, 0));
        ViewPatientJPanel1 selectedPanel = null;
        try {
            selectedPanel = new  ViewPatientJPanel1 (mainWorkArea,encounter,patient);
        } catch (ParseException ex) {
            Logger.getLogger(PatientProfileJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        mainWorkArea.add("EncounterJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        EncounterJPanel selectedPanel =new  EncounterJPanel (mainWorkArea,patient);
        mainWorkArea.add("EncounterJPanel", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea); 
    }//GEN-LAST:event_btnAddActionPerformed
    
    void refreshTable() {
        DefaultTableModel model = (DefaultTableModel)tblHistory.getModel();
            model.setRowCount(0);
            for(Encounter e: patient.getEncounterHistory()) {
                    Object row[] = new Object[3];
                    row[0] = e;
                    row[1] = e.getVitalSigns().getBp();
                    row[2] = e.getVitalSigns().getTemp();
                   // row[1] = s.getProductCatalog().getProductCount() == 0 ? "None" : s.getProductCatalog().getProductCount();
                    model.addRow(row);
        }
    }
    private void txtGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGenderActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComActionPerformed

    private void txtStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PersonaljPanel;
    private javax.swing.JPanel PersonaljPanel1;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdd;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCom;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblHistory;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtAdd1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCom;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtState;
    // End of variables declaration//GEN-END:variables

   
}
