/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.AddressInfo;

/**
 *
 * @author Aishwarya
 */
public class AddressJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddressJPanel
     */
    AddressInfo addressInfo;
    public AddressJPanel(AddressInfo addressInfo) {
        initComponents();
        this.addressInfo = addressInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblStreet2 = new javax.swing.JLabel();
        lblStreet1 = new javax.swing.JLabel();
        lblPinCode = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        txtStreet1 = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtStreet2 = new javax.swing.JTextField();
        txtState = new javax.swing.JTextField();
        txtPincode = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setForeground(new java.awt.Color(99, 119, 145));

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Address Information Form");

        lblCity.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(99, 119, 145));
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCity.setText("City:");

        lblStreet2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblStreet2.setForeground(new java.awt.Color(99, 119, 145));
        lblStreet2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreet2.setText("Street 2:");

        lblStreet1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblStreet1.setForeground(new java.awt.Color(99, 119, 145));
        lblStreet1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStreet1.setText("Street 1:");

        lblPinCode.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblPinCode.setForeground(new java.awt.Color(99, 119, 145));
        lblPinCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPinCode.setText("Pin Code:");

        lblState.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(99, 119, 145));
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblState.setText("State:");

        lblCountry.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(99, 119, 145));
        lblCountry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCountry.setText("Country:");

        txtStreet1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCity.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtStreet2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtState.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPincode.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtCountry.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(26, 79, 130));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStreet2)
                    .addComponent(lblStreet1)
                    .addComponent(lblState)
                    .addComponent(lblCity)
                    .addComponent(lblPinCode)
                    .addComponent(lblCountry))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet1)
                    .addComponent(txtStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStreet2)
                    .addComponent(txtStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPinCode)
                    .addComponent(txtPincode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtStreet1.getText().isEmpty()||txtStreet2.getText().isEmpty()||txtCity.getText().isEmpty()||txtState.getText().isEmpty()||txtCountry.getText().isEmpty()||txtPincode.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please fillup all the fields","Error",JOptionPane.ERROR_MESSAGE); 
        } else{
            int pin = 0;
            try{
                pin = Integer.parseInt(txtPincode.getText()); 
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Please enter PINCODE in numerical format");
                return;
            }
            addressInfo.setStreet1(txtStreet1.getText());
            addressInfo.setStreet2(txtStreet2.getText());
            addressInfo.setCity(txtCity.getText());
            addressInfo.setState(txtState.getText());
            addressInfo.setCountry(txtCountry.getText());
            addressInfo.setPin(pin);
            JOptionPane.showMessageDialog(this, "Address Information Submitted!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblStreet2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreet1;
    private javax.swing.JTextField txtStreet2;
    // End of variables declaration//GEN-END:variables
}
