/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.CheckingAccount;

/**
 *
 * @author Aishwarya
 */
public class CheckingAccJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CheckingAccJPanel
     */
    CheckingAccount checkingAccount;
    public CheckingAccJPanel(CheckingAccount checkingAccount) {
        initComponents();
        this.checkingAccount = checkingAccount;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAccNum = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblBankRoutNum = new javax.swing.JLabel();
        lblAccBalance = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        txtBankRoutNo = new javax.swing.JTextField();
        txtBankName = new javax.swing.JTextField();
        txtAccNum = new javax.swing.JTextField();
        txtAccBal = new javax.swing.JTextField();
        txtAccType = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblAccNum.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAccNum.setForeground(new java.awt.Color(99, 119, 145));
        lblAccNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccNum.setText("Bank Account Number:");

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Checking Account Information Form");

        lblBankName.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblBankName.setForeground(new java.awt.Color(99, 119, 145));
        lblBankName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankName.setText("Bank Name:");

        lblBankRoutNum.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblBankRoutNum.setForeground(new java.awt.Color(99, 119, 145));
        lblBankRoutNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBankRoutNum.setText("Bank Routing Number:");

        lblAccBalance.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAccBalance.setForeground(new java.awt.Color(99, 119, 145));
        lblAccBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccBalance.setText("Account Balance:");

        lblAccType.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAccType.setForeground(new java.awt.Color(99, 119, 145));
        lblAccType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAccType.setText("Account Type: ");

        txtBankRoutNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtBankName.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccBal.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAccType.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        txtAccType.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAccType.setText("Checking");
        txtAccType.setEnabled(false);
        txtAccType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAccTypeActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(26, 79, 130));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblBankRoutNum)
                            .addComponent(lblBankName)
                            .addComponent(lblAccBalance)
                            .addComponent(lblAccNum)
                            .addComponent(lblAccType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBankRoutNo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankName)
                    .addComponent(txtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBankRoutNum)
                    .addComponent(txtBankRoutNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccNum)
                    .addComponent(txtAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccBalance)
                    .addComponent(txtAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccType)
                    .addComponent(txtAccType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAccTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAccTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAccTypeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       if(txtAccBal.getText().isEmpty()||txtAccNum.getText().isEmpty()||txtAccType.getText().isEmpty()||txtBankName.getText().isEmpty()||txtBankRoutNo.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Please fillup all the fields","Error",JOptionPane.ERROR_MESSAGE); 
        } else{
           double accBal = 0.0;
           int accNum = 0;
           try{
               accBal = Double.parseDouble(txtAccBal.getText());
               accNum = Integer.parseInt(txtAccNum.getText());
           }catch(Exception e){
               JOptionPane.showMessageDialog(this, "Please enter Account Balance and Account Number in valid format");
               return;
           }
           checkingAccount.setAccountBalance(accBal);
           checkingAccount.setAccountType(txtAccType.getText());
           checkingAccount.setBankAccNum(accNum);
           checkingAccount.setBankName(txtBankName.getText());
           checkingAccount.setBankRoutingNum(txtBankRoutNo.getText());
           JOptionPane.showMessageDialog(this, "Checking Account Information Submitted!");
       }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAccBalance;
    private javax.swing.JLabel lblAccNum;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblBankRoutNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAccBal;
    private javax.swing.JTextField txtAccNum;
    private javax.swing.JTextField txtAccType;
    private javax.swing.JTextField txtBankName;
    private javax.swing.JTextField txtBankRoutNo;
    // End of variables declaration//GEN-END:variables
}
