/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.DriverLicense;

/**
 *
 * @author Aishwarya
 */
public class DriverLicenseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverLicenseJPanel
     */
    File file;
    DriverLicense driverLicense;
    FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
    public DriverLicenseJPanel(DriverLicense driverLicense) {
        initComponents();
        FileFilter imageFilter = new FileNameExtensionFilter("Image files", ImageIO.getReaderFileSuffixes());
        fileChooser.setFileFilter(imageFilter);
        this.driverLicense = driverLicense;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        lbDOE = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblDOI = new javax.swing.JLabel();
        lblAccBalance = new javax.swing.JLabel();
        lblAccType = new javax.swing.JLabel();
        txtLicenseNum = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jcbBloodGrp = new javax.swing.JComboBox<>();
        jdcDOI = new com.toedter.calendar.JDateChooser();
        jdcDOE = new com.toedter.calendar.JDateChooser();
        btnBrowse = new javax.swing.JButton();

        setForeground(new java.awt.Color(99, 119, 145));

        lbDOE.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lbDOE.setForeground(new java.awt.Color(99, 119, 145));
        lbDOE.setText("Date of Expiration:");

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Driver's License Information Form");

        lblLicenseNum.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblLicenseNum.setForeground(new java.awt.Color(99, 119, 145));
        lblLicenseNum.setText("License Number:");

        lblDOI.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblDOI.setForeground(new java.awt.Color(99, 119, 145));
        lblDOI.setText("Date of Issue:");

        lblAccBalance.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAccBalance.setForeground(new java.awt.Color(99, 119, 145));
        lblAccBalance.setText("Blood Type:");

        lblAccType.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAccType.setForeground(new java.awt.Color(99, 119, 145));
        lblAccType.setText("Picture:");

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(26, 79, 130));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jcbBloodGrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(226, 226, 226))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDOI)
                            .addComponent(lblLicenseNum)
                            .addComponent(lblAccBalance)
                            .addComponent(lbDOE)
                            .addComponent(lblAccType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLicenseNum)
                                .addComponent(jcbBloodGrp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcDOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jdcDOE, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                            .addComponent(btnBrowse))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum)
                    .addComponent(txtLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDOI)
                    .addComponent(jdcDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDOE)
                    .addComponent(jdcDOE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccBalance)
                    .addComponent(jcbBloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAccType)
                    .addComponent(btnBrowse))
                .addGap(27, 27, 27)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if(txtLicenseNum.getText().isEmpty() ||jdcDOE.getDate() == null ||jdcDOI.getDate() == null){
            JOptionPane.showMessageDialog(null, "Please fillup all the fields","Error",JOptionPane.ERROR_MESSAGE);
        } else{
            int check = jdcDOE.getDate().compareTo(jdcDOI.getDate());
            if(check < 0){
                JOptionPane.showMessageDialog(null, "Date of Expiration should be after Date of Issue","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            driverLicense.setLicenseNum(txtLicenseNum.getText());
            driverLicense.setDOI(fmt.format(jdcDOI.getDate()));
            driverLicense.setDOE(fmt.format(jdcDOE.getDate()));
            driverLicense.setBloodType((String) jcbBloodGrp.getSelectedItem());
            driverLicense.setPicture(file);
            JOptionPane.showMessageDialog(this, "Driver's License Information Submitted!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        int returnVal = fileChooser.showDialog(this,"Attach");
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            file = fileChooser.getSelectedFile();
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnBrowseActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSave;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JComboBox<String> jcbBloodGrp;
    private com.toedter.calendar.JDateChooser jdcDOE;
    private com.toedter.calendar.JDateChooser jdcDOI;
    private javax.swing.JLabel lbDOE;
    private javax.swing.JLabel lblAccBalance;
    private javax.swing.JLabel lblAccType;
    private javax.swing.JLabel lblDOI;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtLicenseNum;
    // End of variables declaration//GEN-END:variables
}
