/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JOptionPane;
import model.MedicalRecord;

/**
 *
 * @author Aishwarya
 */
public class MedicalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalJPanel
     */
    MedicalRecord medicalRecord;
    public MedicalJPanel(MedicalRecord medicalRecord) {
        initComponents();
        this.medicalRecord = medicalRecord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblMedicalRecordNum = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        txtMedicalRecordNum = new javax.swing.JTextField();
        txtAlergy1 = new javax.swing.JTextField();
        txtAlergy2 = new javax.swing.JTextField();
        txtAlergy3 = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Medical Record Form");

        lblAlergy2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAlergy2.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlergy2.setText("Alergy 2:");

        lblMedicalRecordNum.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblMedicalRecordNum.setForeground(new java.awt.Color(99, 119, 145));
        lblMedicalRecordNum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMedicalRecordNum.setText("Medical record Number:");

        lblAlergy1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAlergy1.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAlergy1.setText("Alergy 1:");

        lblAlergy3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        lblAlergy3.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy3.setText("Alergy 3:");

        txtMedicalRecordNum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlergy1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlergy2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtAlergy3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSave.setForeground(new java.awt.Color(26, 79, 130));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAlergy1)
                            .addComponent(lblMedicalRecordNum)
                            .addComponent(lblAlergy3)
                            .addComponent(lblAlergy2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblTitle)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicalRecordNum)
                    .addComponent(txtMedicalRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy1)
                    .addComponent(txtAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy2)
                    .addComponent(txtAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy3)
                    .addComponent(txtAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(txtAlergy1.getText().isEmpty()||txtAlergy2.getText().isEmpty()|| txtAlergy3.getText().isEmpty()|| txtMedicalRecordNum.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please fillup all the fields","Error",JOptionPane.ERROR_MESSAGE); 
        } else {
            int medicalRec = 0;
            try{
                medicalRec = Integer.parseInt(txtMedicalRecordNum.getText()); 
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Please enter Medical Record Number in numerical format");
                return;
            }
            medicalRecord.setMedicalRecordNum(medicalRec);
            medicalRecord.setAlergy1(txtAlergy1.getText());
            medicalRecord.setAlergy2(txtAlergy2.getText());
            medicalRecord.setAlergy3(txtAlergy3.getText());
            JOptionPane.showMessageDialog(this, "Medical Record Information Submitted!");
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblMedicalRecordNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAlergy1;
    private javax.swing.JTextField txtAlergy2;
    private javax.swing.JTextField txtAlergy3;
    private javax.swing.JTextField txtMedicalRecordNum;
    // End of variables declaration//GEN-END:variables
}
