/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import model.AddressInfo;
import model.CheckingAccount;
import model.DemographicInfo;
import model.DriverLicense;
import model.MedicalRecord;
import model.SavingAccount;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
/**
 *
 * @author Aishwarya
 */
public class ViewInfoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInfoJPanel
     */
    AddressInfo addressInfo;
    CheckingAccount checkingAccount;
    DemographicInfo demographicInfo;
    DriverLicense driverLicense;
    MedicalRecord medicalRecord;
    SavingAccount savingAccount;
    
    public ViewInfoJPanel(AddressInfo addressInfo,CheckingAccount checkingAccount,DemographicInfo demographicInfo,DriverLicense driverLicense,MedicalRecord medicalRecord,SavingAccount savingAccount) throws IOException {
        initComponents();
        this.addressInfo = addressInfo;
        this.checkingAccount = checkingAccount;
        this.demographicInfo =demographicInfo;
        this.driverLicense =driverLicense;
        this.medicalRecord = medicalRecord;
        this.savingAccount = savingAccount;
        
        getDemographicInfo();
        getAddressInformation();
        getCheckingAccountInfo();
        getSavingAccountInfo();
        getDriverLicenseInfo();
        getMedicalRecord();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DemoJPanel = new javax.swing.JPanel();
        lblFNameTitle = new javax.swing.JLabel();
        lblLNameTitle = new javax.swing.JLabel();
        lblAgeTitle = new javax.swing.JLabel();
        lblDOBTitle = new javax.swing.JLabel();
        lblHeightTitle = new javax.swing.JLabel();
        lblWeightTitle = new javax.swing.JLabel();
        lblPhoneTitle = new javax.swing.JLabel();
        lblSSNTitle = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        addressJPanel = new javax.swing.JPanel();
        lblStreet1 = new javax.swing.JLabel();
        lblStreet2 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblState = new javax.swing.JLabel();
        lblPin = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        savingJPanel = new javax.swing.JPanel();
        lblSavNameTitle = new javax.swing.JLabel();
        lblSavAccNumTitle = new javax.swing.JLabel();
        lblSavRoutNumTitle = new javax.swing.JLabel();
        lblSavAccTypeTitle = new javax.swing.JLabel();
        lblSavAccBalTitle = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSavName = new javax.swing.JLabel();
        lblSavAccNum = new javax.swing.JLabel();
        lblSavAccBal = new javax.swing.JLabel();
        lblSavRoutNum = new javax.swing.JLabel();
        lblSavAccType = new javax.swing.JLabel();
        checkingJPanel = new javax.swing.JPanel();
        lblChNameTitle = new javax.swing.JLabel();
        lblChRoutNumTitle = new javax.swing.JLabel();
        lblChAccNumTitle = new javax.swing.JLabel();
        lblChAccTypeTitle = new javax.swing.JLabel();
        lblChAccBalTitle = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblChName = new javax.swing.JLabel();
        lblChAccNum = new javax.swing.JLabel();
        lblChAccBal = new javax.swing.JLabel();
        lblChRoutNum = new javax.swing.JLabel();
        lblChAccType = new javax.swing.JLabel();
        driverJPanel = new javax.swing.JPanel();
        lblTitle2 = new javax.swing.JLabel();
        lblLicenseNum = new javax.swing.JLabel();
        lblDOI = new javax.swing.JLabel();
        lblDOE = new javax.swing.JLabel();
        lblBloodType = new javax.swing.JLabel();
        lblLNum = new javax.swing.JLabel();
        lblLDOI = new javax.swing.JLabel();
        lblLBloodType = new javax.swing.JLabel();
        lblLDOE = new javax.swing.JLabel();
        medicalJPanel = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        lblMedRecordNum = new javax.swing.JLabel();
        lblAlergy1 = new javax.swing.JLabel();
        lblAlergy2 = new javax.swing.JLabel();
        lblAlergy3 = new javax.swing.JLabel();
        lblMedNum = new javax.swing.JLabel();
        lblTxtAlert2 = new javax.swing.JLabel();
        lblTxtAlert1 = new javax.swing.JLabel();
        lblTxtAlert3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();

        DemoJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Demographic Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 1, 16), new java.awt.Color(72, 55, 123))); // NOI18N
        DemoJPanel.setPreferredSize(new java.awt.Dimension(408, 189));
        DemoJPanel.setForeground(new java.awt.Color(30, 17, 146));

        lblFNameTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblFNameTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblFNameTitle.setText("First Name:");

        lblLNameTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLNameTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblLNameTitle.setText("Last Name:");

        lblAgeTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblAgeTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblAgeTitle.setText("Age:");

        lblDOBTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDOBTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblDOBTitle.setText("Date of Birth:");

        lblHeightTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblHeightTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblHeightTitle.setText("Height:");

        lblWeightTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblWeightTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblWeightTitle.setText("Weight:");

        lblPhoneTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPhoneTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblPhoneTitle.setText("Phone Number:");

        lblSSNTitle.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblSSNTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSSNTitle.setText("Social Security Number:");

        lblFirst.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblFirst.setForeground(new java.awt.Color(99, 119, 145));
        lblFirst.setText("First Name:");

        lblLast.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLast.setForeground(new java.awt.Color(99, 119, 145));
        lblLast.setText("First Name:");

        lblDOB.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(99, 119, 145));
        lblDOB.setText("First Name:");

        lblAge.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblAge.setForeground(new java.awt.Color(99, 119, 145));
        lblAge.setText("First Name:");

        lblWeight.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblWeight.setForeground(new java.awt.Color(99, 119, 145));
        lblWeight.setText("First Name:");

        lblHeight.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(99, 119, 145));
        lblHeight.setText("First Name:");

        lblPhone.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(99, 119, 145));
        lblPhone.setText("First Name:");

        lblSSN.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblSSN.setForeground(new java.awt.Color(99, 119, 145));
        lblSSN.setText("First Name:");

        javax.swing.GroupLayout DemoJPanelLayout = new javax.swing.GroupLayout(DemoJPanel);
        DemoJPanel.setLayout(DemoJPanelLayout);
        DemoJPanelLayout.setHorizontalGroup(
            DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoJPanelLayout.createSequentialGroup()
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DemoJPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblLNameTitle)
                                .addComponent(lblFNameTitle))
                            .addGroup(DemoJPanelLayout.createSequentialGroup()
                                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAgeTitle)
                                    .addComponent(lblDOBTitle))
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSSNTitle)
                        .addComponent(lblPhoneTitle)
                        .addComponent(lblHeightTitle)
                        .addComponent(lblWeightTitle)))
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DemoJPanelLayout.createSequentialGroup()
                        .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLast, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lblDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lblAge, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(lblWeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addComponent(lblHeight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSSN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        DemoJPanelLayout.setVerticalGroup(
            DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DemoJPanelLayout.createSequentialGroup()
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFNameTitle)
                    .addComponent(lblFirst))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLNameTitle)
                    .addComponent(lblLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOBTitle)
                    .addComponent(lblDOB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAgeTitle)
                    .addComponent(lblAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeightTitle)
                    .addComponent(lblWeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeightTitle)
                    .addComponent(lblHeight))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneTitle)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DemoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSNTitle)
                    .addComponent(lblSSN))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Other Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Ubuntu", 1, 16), new java.awt.Color(72, 55, 123))); // NOI18N
        jTabbedPane1.setForeground(new java.awt.Color(72, 55, 123));
        jTabbedPane1.setFont(new java.awt.Font("TlwgTypewriter", 1, 14)); // NOI18N

        addressJPanel.setForeground(new java.awt.Color(40, 73, 122));

        lblStreet1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblStreet1.setForeground(new java.awt.Color(99, 119, 145));
        lblStreet1.setText("Flat no 406, C Building");

        lblStreet2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblStreet2.setForeground(new java.awt.Color(99, 119, 145));
        lblStreet2.setText("Hira Shree lake City, Rankla");

        lblCity.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(99, 119, 145));
        lblCity.setText("Kolhapur");

        lblState.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblState.setForeground(new java.awt.Color(99, 119, 145));
        lblState.setText("Maharashtra");

        lblPin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblPin.setForeground(new java.awt.Color(99, 119, 145));
        lblPin.setText("416012");

        lblCountry.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblCountry.setForeground(new java.awt.Color(99, 119, 145));
        lblCountry.setText("India");

        javax.swing.GroupLayout addressJPanelLayout = new javax.swing.GroupLayout(addressJPanel);
        addressJPanel.setLayout(addressJPanelLayout);
        addressJPanelLayout.setHorizontalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblStreet2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                    .addComponent(lblCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStreet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addressJPanelLayout.setVerticalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblStreet1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStreet2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblState, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Address", addressJPanel);

        lblSavNameTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavNameTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSavNameTitle.setText("Bank Name:");

        lblSavAccNumTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccNumTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccNumTitle.setText("Bank Account Number:");

        lblSavRoutNumTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavRoutNumTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSavRoutNumTitle.setText("Bank Routing Number:");

        lblSavAccTypeTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccTypeTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccTypeTitle.setText("Account Type:");

        lblSavAccBalTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccBalTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccBalTitle.setText("Account Balance:");

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Saving Bank Account Details");

        lblSavName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavName.setForeground(new java.awt.Color(99, 119, 145));
        lblSavName.setText("Bank Routing Number:");

        lblSavAccNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccNum.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccNum.setText("Bank Routing Number:");

        lblSavAccBal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccBal.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccBal.setText("Bank Routing Number:");

        lblSavRoutNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavRoutNum.setForeground(new java.awt.Color(99, 119, 145));
        lblSavRoutNum.setText("Bank Routing Number:");

        lblSavAccType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblSavAccType.setForeground(new java.awt.Color(99, 119, 145));
        lblSavAccType.setText("Bank Routing Number:");

        javax.swing.GroupLayout savingJPanelLayout = new javax.swing.GroupLayout(savingJPanel);
        savingJPanel.setLayout(savingJPanelLayout);
        savingJPanelLayout.setHorizontalGroup(
            savingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(savingJPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(savingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSavNameTitle)
                    .addComponent(lblSavRoutNumTitle)
                    .addComponent(lblSavAccNumTitle)
                    .addComponent(lblSavAccBalTitle)
                    .addComponent(lblSavAccTypeTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(savingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSavName)
                    .addComponent(lblSavAccNum)
                    .addComponent(lblSavAccBal)
                    .addComponent(lblSavRoutNum)
                    .addComponent(lblSavAccType))
                .addContainerGap(123, Short.MAX_VALUE))
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        savingJPanelLayout.setVerticalGroup(
            savingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, savingJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(savingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(savingJPanelLayout.createSequentialGroup()
                        .addComponent(lblSavNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavRoutNumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccNumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccBalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccTypeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(savingJPanelLayout.createSequentialGroup()
                        .addComponent(lblSavName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavRoutNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSavAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Saving", savingJPanel);

        lblChNameTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChNameTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblChNameTitle.setText("Bank Name:");

        lblChRoutNumTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChRoutNumTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblChRoutNumTitle.setText("Bank Routing Number:");

        lblChAccNumTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccNumTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccNumTitle.setText("Bank Account Number:");

        lblChAccTypeTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccTypeTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccTypeTitle.setText("Account Type:");

        lblChAccBalTitle.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccBalTitle.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccBalTitle.setText("Account Balance:");

        lblTitle1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle1.setText("Checking Bank Account Details");

        lblChName.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChName.setForeground(new java.awt.Color(99, 119, 145));
        lblChName.setText("Bank Routing Number:");

        lblChAccNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccNum.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccNum.setText("Bank Routing Number:");

        lblChAccBal.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccBal.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccBal.setText("Bank Routing Number:");

        lblChRoutNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChRoutNum.setForeground(new java.awt.Color(99, 119, 145));
        lblChRoutNum.setText("Bank Routing Number:");

        lblChAccType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblChAccType.setForeground(new java.awt.Color(99, 119, 145));
        lblChAccType.setText("Bank Routing Number:");

        javax.swing.GroupLayout checkingJPanelLayout = new javax.swing.GroupLayout(checkingJPanel);
        checkingJPanel.setLayout(checkingJPanelLayout);
        checkingJPanelLayout.setHorizontalGroup(
            checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkingJPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblChNameTitle)
                    .addComponent(lblChRoutNumTitle)
                    .addComponent(lblChAccNumTitle)
                    .addComponent(lblChAccBalTitle)
                    .addComponent(lblChAccTypeTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblChName)
                    .addComponent(lblChAccNum)
                    .addComponent(lblChAccBal)
                    .addComponent(lblChRoutNum)
                    .addComponent(lblChAccType))
                .addContainerGap(120, Short.MAX_VALUE))
            .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        checkingJPanelLayout.setVerticalGroup(
            checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkingJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitle1)
                .addGap(18, 18, 18)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChNameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChRoutNumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChRoutNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChAccNumTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChAccNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChAccBalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChAccBal, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkingJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChAccTypeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblChAccType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Checking", checkingJPanel);

        lblTitle2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle2.setText("Driver License Details");

        lblLicenseNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLicenseNum.setForeground(new java.awt.Color(99, 119, 145));
        lblLicenseNum.setText("License Number:");

        lblDOI.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDOI.setForeground(new java.awt.Color(99, 119, 145));
        lblDOI.setText("Date of Issue:");

        lblDOE.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblDOE.setForeground(new java.awt.Color(99, 119, 145));
        lblDOE.setText("Date of Expiration:");

        lblBloodType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblBloodType.setForeground(new java.awt.Color(99, 119, 145));
        lblBloodType.setText("Blood Type:");

        lblLNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLNum.setForeground(new java.awt.Color(99, 119, 145));
        lblLNum.setText("License Number:");

        lblLDOI.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLDOI.setForeground(new java.awt.Color(99, 119, 145));
        lblLDOI.setText("License Number:");

        lblLBloodType.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLBloodType.setForeground(new java.awt.Color(99, 119, 145));
        lblLBloodType.setText("License Number:");

        lblLDOE.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLDOE.setForeground(new java.awt.Color(99, 119, 145));
        lblLDOE.setText("License Number:");

        javax.swing.GroupLayout driverJPanelLayout = new javax.swing.GroupLayout(driverJPanel);
        driverJPanel.setLayout(driverJPanelLayout);
        driverJPanelLayout.setHorizontalGroup(
            driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLicenseNum)
                    .addComponent(lblDOI)
                    .addComponent(lblDOE)
                    .addComponent(lblBloodType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLNum, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(lblLDOI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLDOE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, driverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        driverJPanelLayout.setVerticalGroup(
            driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(driverJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLicenseNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLDOE, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(driverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Driver's License", driverJPanel);

        lblTitle3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(72, 55, 123));
        lblTitle3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle3.setText("Medical Record Details");

        lblMedRecordNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMedRecordNum.setForeground(new java.awt.Color(99, 119, 145));
        lblMedRecordNum.setText("Medical Record Number:");

        lblAlergy1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAlergy1.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy1.setText("Alergy 1:");

        lblAlergy2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAlergy2.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy2.setText("Alergy 2:");

        lblAlergy3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblAlergy3.setForeground(new java.awt.Color(99, 119, 145));
        lblAlergy3.setText("Alergy 3:");

        lblMedNum.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblMedNum.setForeground(new java.awt.Color(99, 119, 145));
        lblMedNum.setText("Medical Record Number:");

        lblTxtAlert2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTxtAlert2.setForeground(new java.awt.Color(99, 119, 145));
        lblTxtAlert2.setText("Medical Record Number:");

        lblTxtAlert1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTxtAlert1.setForeground(new java.awt.Color(99, 119, 145));
        lblTxtAlert1.setText("Medical Record Number:");

        lblTxtAlert3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblTxtAlert3.setForeground(new java.awt.Color(99, 119, 145));
        lblTxtAlert3.setText("Medical Record Number:");

        javax.swing.GroupLayout medicalJPanelLayout = new javax.swing.GroupLayout(medicalJPanel);
        medicalJPanel.setLayout(medicalJPanelLayout);
        medicalJPanelLayout.setHorizontalGroup(
            medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalJPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblMedRecordNum)
                    .addComponent(lblAlergy1)
                    .addComponent(lblAlergy2)
                    .addComponent(lblAlergy3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMedNum)
                    .addComponent(lblTxtAlert2)
                    .addComponent(lblTxtAlert1)
                    .addComponent(lblTxtAlert3))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, medicalJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        medicalJPanelLayout.setVerticalGroup(
            medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(medicalJPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedRecordNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedNum, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtAlert1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtAlert2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(medicalJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergy3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTxtAlert3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Medical Record", medicalJPanel);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Picture", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Ubuntu", 1, 15), new java.awt.Color(72, 55, 123))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(DemoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DemoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DemoJPanel;
    private javax.swing.JPanel addressJPanel;
    private javax.swing.JPanel checkingJPanel;
    private javax.swing.JPanel driverJPanel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblAgeTitle;
    private javax.swing.JLabel lblAlergy1;
    private javax.swing.JLabel lblAlergy2;
    private javax.swing.JLabel lblAlergy3;
    private javax.swing.JLabel lblBloodType;
    private javax.swing.JLabel lblChAccBal;
    private javax.swing.JLabel lblChAccBalTitle;
    private javax.swing.JLabel lblChAccNum;
    private javax.swing.JLabel lblChAccNumTitle;
    private javax.swing.JLabel lblChAccType;
    private javax.swing.JLabel lblChAccTypeTitle;
    private javax.swing.JLabel lblChName;
    private javax.swing.JLabel lblChNameTitle;
    private javax.swing.JLabel lblChRoutNum;
    private javax.swing.JLabel lblChRoutNumTitle;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOBTitle;
    private javax.swing.JLabel lblDOE;
    private javax.swing.JLabel lblDOI;
    private javax.swing.JLabel lblFNameTitle;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeightTitle;
    private javax.swing.JLabel lblLBloodType;
    private javax.swing.JLabel lblLDOE;
    private javax.swing.JLabel lblLDOI;
    private javax.swing.JLabel lblLNameTitle;
    private javax.swing.JLabel lblLNum;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblLicenseNum;
    private javax.swing.JLabel lblMedNum;
    private javax.swing.JLabel lblMedRecordNum;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoneTitle;
    private javax.swing.JLabel lblPin;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblSSNTitle;
    private javax.swing.JLabel lblSavAccBal;
    private javax.swing.JLabel lblSavAccBalTitle;
    private javax.swing.JLabel lblSavAccNum;
    private javax.swing.JLabel lblSavAccNumTitle;
    private javax.swing.JLabel lblSavAccType;
    private javax.swing.JLabel lblSavAccTypeTitle;
    private javax.swing.JLabel lblSavName;
    private javax.swing.JLabel lblSavNameTitle;
    private javax.swing.JLabel lblSavRoutNum;
    private javax.swing.JLabel lblSavRoutNumTitle;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblStreet2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTxtAlert1;
    private javax.swing.JLabel lblTxtAlert2;
    private javax.swing.JLabel lblTxtAlert3;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JLabel lblWeightTitle;
    private javax.swing.JPanel medicalJPanel;
    private javax.swing.JPanel savingJPanel;
    // End of variables declaration//GEN-END:variables

    private void getDemographicInfo() {
        lblFirst.setText(demographicInfo.getFirstName());
        lblLast.setText(demographicInfo.getLastName());
        lblPhone.setText(String.valueOf(demographicInfo.getPhoneNum()));
        lblDOB.setText(String.valueOf(demographicInfo.getDOB()));
        lblAge.setText(String.valueOf(demographicInfo.getAge()));
        lblHeight.setText(String.valueOf(demographicInfo.getHeight()));
        lblWeight.setText(String.valueOf(demographicInfo.getWeight()));
        lblSSN.setText(demographicInfo.getSSN());
    }

    private void getAddressInformation() {
        lblStreet1.setText(addressInfo.getStreet1());
        lblStreet2.setText(addressInfo.getStreet2());
        lblCity.setText(addressInfo.getCity());
        lblState.setText(addressInfo.getState());
        lblCountry.setText(addressInfo.getCountry());
        lblPin.setText(String.valueOf(addressInfo.getPin()));
    }

    private void getCheckingAccountInfo() {
        lblChAccBal.setText(String.valueOf(checkingAccount.getAccountBalance()));
        lblChAccNum.setText(String.valueOf(checkingAccount.getBankAccNum()));
        lblChAccType.setText(checkingAccount.getAccountType());
        lblChRoutNum.setText(checkingAccount.getBankRoutingNum());
        lblChName.setText(checkingAccount.getBankName());
    }

    private void getSavingAccountInfo() {
        lblSavAccBal.setText(String.valueOf(savingAccount.getAccountBalance()));
        lblSavAccNum.setText(String.valueOf(savingAccount.getBankAccNum()));
        lblSavAccType.setText(savingAccount.getAccountType());
        lblSavRoutNum.setText(savingAccount.getBankRoutingNum());
        lblSavName.setText(savingAccount.getBankName());
    }

    private void getDriverLicenseInfo() throws IOException {
        lblLBloodType.setText(driverLicense.getBloodType());
        lblLDOI.setText(String.valueOf(driverLicense.getDOI()));
        lblLDOE.setText(String.valueOf(driverLicense.getDOE()));
        lblLNum.setText(String.valueOf(driverLicense.getLicenseNum()));
        scaleImage();
    }

    private void getMedicalRecord() {
        lblMedNum.setText(String.valueOf(medicalRecord.getMedicalRecordNum()));
        lblTxtAlert1.setText(medicalRecord.getAlergy1());
        lblTxtAlert2.setText(medicalRecord.getAlergy2());
        lblTxtAlert3.setText(medicalRecord.getAlergy3());
    }
    public void scaleImage(){
        try{
            File file = driverLicense.getPicture();
            if(file != null){
                ImageIcon imageicon = new ImageIcon(ImageIO.read(file));
                Image icon = imageicon.getImage();
                Image scaledImg = icon.getScaledInstance(150, 180, Image.SCALE_SMOOTH);
                ImageIcon imgScaled = new ImageIcon(scaledImg);
                image.setIcon(imgScaled);
            }else {
                image.setText("Not Uploaded");
            }
            
        }catch(IOException e){
            JOptionPane.showMessageDialog(this, "Please upload the Image in Driver's License");
        }
    }
}
