/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import ui.person.PersonDirectoryJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.person.PersonDirectory;
import model.patient.PatientDirectory;
import ui.patient.PatientDirectoryJPanel;

/**
 *
 * @author archil
 */
public class LoginScreen extends javax.swing.JPanel {

    JPanel mainWorkArea;
    
    
    /**
     * Creates new form LoginScreen
     */
    private PersonDirectory personDirectory;
    private PatientDirectory patientDirectory;
    public LoginScreen(JPanel mainWorkArea,PersonDirectory personDirectory,PatientDirectory patientDirectory) {
        initComponents();
        
        this.mainWorkArea = mainWorkArea;
        this.personDirectory =personDirectory;
        this.patientDirectory = patientDirectory;
         populateRoleCombo();
//        populateSupplierCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbRoles = new javax.swing.JComboBox<>();
        lblRole = new javax.swing.JLabel();
        lblRole1 = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        cmbRoles.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmbRoles.setForeground(new java.awt.Color(65, 82, 118));
        cmbRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRolesActionPerformed(evt);
            }
        });

        lblRole.setBackground(new java.awt.Color(254, 254, 254));
        lblRole.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblRole.setForeground(new java.awt.Color(61, 118, 165));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Person's Medical Records");

        lblRole1.setBackground(new java.awt.Color(254, 254, 254));
        lblRole1.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblRole1.setForeground(new java.awt.Color(114, 150, 180));
        lblRole1.setText("Choose Role :");

        btnLogin.setBackground(new java.awt.Color(254, 254, 254));
        btnLogin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(229, 70, 69));
        btnLogin.setText("LOGIN");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblRole1)
                        .addGap(18, 18, 18)
                        .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblRole, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRole1))
                .addGap(41, 41, 41)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(307, 307, 307))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRolesActionPerformed
        // TODO add your handling code here:
        updateSupplierVisibility();
    }//GEN-LAST:event_cmbRolesActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        JPanel selectedPanel;
        if("Patient Directory".equals(cmbRoles.getSelectedItem())){
           selectedPanel = new PatientDirectoryJPanel(mainWorkArea,patientDirectory,personDirectory);
        } else{
            selectedPanel = new PersonDirectoryJPanel(mainWorkArea,personDirectory);
        }
//       PatientDirectoryJPanel adminPanel = new PatientDirectoryJPanel(mainWorkArea,patientDirectory,personDirectory);
//       PersonDirectoryJPanel supplierPanel = new PersonDirectoryJPanel(mainWorkArea,personDirectory);
//        JPanel selectedPanel = (JPanel) cmbRoles.getSelectedItem();
//        if(selectedPanel.getClass() == PersonDirectoryJPanel.class){
//            selectedPanel = new PersonDirectoryJPanel(mainWorkArea,personDirectory);
//        } else {
//            selectedPanel = new PatientDirectoryJPanel(mainWorkArea,patientDirectory,personDirectory);
//        }
        //        PersonDirectoryJPanel selectedPanel =new  PersonDirectoryJPanel (mainWorkArea);
        mainWorkArea.add("WorkDirectory", selectedPanel);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<Object> cmbRoles;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblRole1;
    // End of variables declaration//GEN-END:variables

    private void populateRoleCombo() {
       cmbRoles.removeAllItems();
       
       cmbRoles.addItem("Person Directory");
       cmbRoles.addItem("Patient Directory");
    }

//    public void populateSupplierCombo() {
//       cmbSuppliers.removeAllItems();
//       for(Supplier supplier : supplierDirectory.getSupplierList()){
//           cmbSuppliers.addItem(supplier);
//       }
//    }

    private void updateSupplierVisibility() {
        if((cmbRoles.getSelectedItem().getClass()== PersonDirectoryJPanel.class)){
            return;
        }
        
        if(cmbRoles.getSelectedItem().getClass()== PatientDirectoryJPanel.class){
            return;
        }
    }
    
}
