/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JPanel;
import model.university.University;
import model.university.UniversityDirectory;

/**
 *
 * @author dhairyasheel
 */
public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    JPanel mainWorkArea;
    public LoginScreen(JPanel mainWorkArea) {
        initComponents();
        this.mainWorkArea = mainWorkArea;
        populateUniversityCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRole2 = new javax.swing.JLabel();
        cmbUniversity = new javax.swing.JComboBox<>();
        btnLogin = new javax.swing.JButton();
        lblRole1 = new javax.swing.JLabel();
        btnGradesMatter = new javax.swing.JButton();
        lblLgls = new javax.swing.JLabel();
        lblLgas = new javax.swing.JLabel();
        lblLghs = new javax.swing.JLabel();
        lblHgls = new javax.swing.JLabel();
        lblHghs = new javax.swing.JLabel();
        lblHgas = new javax.swing.JLabel();

        setBackground(new java.awt.Color(254, 254, 254));

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblRole2.setBackground(new java.awt.Color(254, 254, 254));
        lblRole2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblRole2.setForeground(new java.awt.Color(37, 106, 162));
        lblRole2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole2.setText("University");

        cmbUniversity.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        cmbUniversity.setForeground(new java.awt.Color(65, 82, 118));
        cmbUniversity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select University" }));
        cmbUniversity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUniversityActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(254, 254, 254));
        btnLogin.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(229, 70, 69));
        btnLogin.setText("View");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(cmbUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(lblRole2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRole2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(cmbUniversity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        lblRole1.setBackground(new java.awt.Color(254, 254, 254));
        lblRole1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        lblRole1.setForeground(new java.awt.Color(4, 95, 169));
        lblRole1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole1.setText("University Model");

        btnGradesMatter.setBackground(new java.awt.Color(254, 254, 254));
        btnGradesMatter.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btnGradesMatter.setForeground(new java.awt.Color(229, 70, 69));
        btnGradesMatter.setText("Do grades matter?");
        btnGradesMatter.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnGradesMatter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradesMatterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRole1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(307, 307, 307))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGradesMatter, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(422, 422, 422))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblHgas, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblHghs, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHgls, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLghs, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLgas, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLgls, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(243, 243, 243))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblHgas, lblHghs, lblHgls, lblLgas, lblLghs, lblLgls});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lblRole1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGradesMatter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLgls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLgas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLghs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHgls, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(lblHgas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHghs, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbUniversityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUniversityActionPerformed
        // TODO add your handling code here:
//        updateSupplierVisibility();
    }//GEN-LAST:event_cmbUniversityActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
            University selectedUni = (University) cmbUniversity.getSelectedItem();
            UniDepartmentJPanel departmentJPanel = new UniDepartmentJPanel(mainWorkArea, selectedUni);
             mainWorkArea.add("UniDepartmentJPanel", departmentJPanel);
              CardLayout layout = (CardLayout) mainWorkArea.getLayout();
             layout.next(mainWorkArea);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnGradesMatterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradesMatterActionPerformed
        // TODO add your handling code here:
        Map relationStats =  UniversityDirectory.calcAlumniGpaSuccessRelationship();
        lblLgls.setText(String.valueOf(relationStats.get("lgls"))+ "% of graduates have low GPA had a low salary");
        lblLgas.setText(String.valueOf(relationStats.get("lgas"))+ "% of graduates have low GPA had a average salary");
        lblLghs.setText(String.valueOf(relationStats.get("lghs"))+ "% of graduates have low GPA had a high salary");
        lblHgls.setText(String.valueOf(relationStats.get("hgls"))+ "% of graduates have high GPA had a low salary");
        lblHgas.setText(String.valueOf(relationStats.get("hgas"))+ "% of graduates have high GPA had a average salary");
        lblHghs.setText(String.valueOf(relationStats.get("hghs"))+ "% of graduates have high GPA had a high salary");
    }//GEN-LAST:event_btnGradesMatterActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGradesMatter;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<Object> cmbUniversity;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHgas;
    private javax.swing.JLabel lblHghs;
    private javax.swing.JLabel lblHgls;
    private javax.swing.JLabel lblLgas;
    private javax.swing.JLabel lblLghs;
    private javax.swing.JLabel lblLgls;
    private javax.swing.JLabel lblRole1;
    private javax.swing.JLabel lblRole2;
    // End of variables declaration//GEN-END:variables

    private void populateUniversityCombo() {
        cmbUniversity.removeAllItems();
        for (University univ : UniversityDirectory.getUniversityList()) {
            cmbUniversity.addItem(univ);
        }
    }
}
